version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  # Mount local frontend code directory into the container
    environment:
      - NODE_ENV=development
    restart: always

  backend:
    build: .  # Assuming backend code is in the root directory
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount local backend code directory into the container
    environment:
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DATABASE=${PG_DATABASE}
      - POSTGRES_PORT=${PG_PORT}
    restart: always
