version: '3.8'

services:
  frontend:
    build: ./client    # Update the path to the frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    image: ali008009/todoapp-backend
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DATABASE=${PG_DATABASE}
      - POSTGRES_PORT=${PG_PORT}
    restart: always
