name: Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install Backend Dependencies
        run: npm install

      - name: Deploy Backend
        run: |
          cd $GITHUB_WORKSPACE  # Change to the root directory
          npm run deploy-backend
