name: Full Stack Deployment

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install Backend Dependencies
        run: npm install

      - name: Deploy Backend to AWS
        run: npm run deploy-backend  # Replace with your deployment command

  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install Frontend Dependencies
        run: |
          cd client  # Change to the client directory
          npm install

      - name: Build Frontend
        run: |
          cd client  # Change to the client directory
          npm run build

      - name: Deploy Frontend to AWS S3
        run: aws s3 sync ./client/build s3://your-s3-bucket  # Replace with your S3 deployment command
