name: Frontend S3 Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.4   # Update to a version compatible with Node.js 20

      - name: Setup Node.js
        uses: actions/setup-node@v4   # Update to a version compatible with Node.js 20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build static file
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://ali-s3-todo-app
