name: Frontend S3 Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Set this to the version in your .nvmrc file

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm --prefix client install

      - name: Build static file
        run: npm --prefix client run build  # Adjust this if your build script is different

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./client/build s3://ali-s3-todo-app
