name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Clean node_modules
        run: rm -rf node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Debug information
        run: |
          node --version
          npm --version
          npm list bcrypt
          ls -al
          cat /home/runner/.npm/_logs/2024-01-29T22_28_16_776Z-debug.log
