name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host 18.133.221.125\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 18.133.221.125 >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa.pub

      - name: Copy files to EC2
        run: scp -o StrictHostKeyChecking=no -r ./ ubuntu@18.133.221.125:~/todo-App

      - name: SSH into EC2, pull changes, and restart
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.133.221.125 "cd ~/todo-App && git pull origin main && npm install && pm2 restart todo-App"
