name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create private key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        shell: bash

      - name: Set correct permissions
        run: chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-18-133-221-125.eu-west-2.compute.amazonaws.com "cd ~/todo-App && git pull origin main"
        shell: bash
