name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create private key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa

      - name: Set correct permissions
        run: chmod 600 /tmp/id_rsa

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -r ./ ubuntu@ec2-18-133-221-125.eu-west-2.compute.amazonaws.com:~/todo-App
          ssh -v -o StrictHostKeyChecking=no -i /tmp/id_rsa ubuntu@ec2-18-133-221-125.eu-west-2.compute.amazonaws.com "cd ~/todo-App && git pull origin main && npm install && pm2 restart todo-App"
