name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.133.221.125 >> ~/.ssh/known_hosts

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todoapp-backend .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todoapp-backend

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: 18.133.221.125
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './*'
          target: '/home/ubuntu/todo-App/'

      - name: SSH into EC2, pull changes, and restart
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh  -i private_key ubuntu@18.133.221.125 "cd ~/todo-App && npm install && pm2 restart todo-App"
