name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        run: scp -o StrictHostKeyChecking=no -i "${{ secrets.SSH_PRIVATE_KEY }}" -r ./ ubuntu@ec2-18-133-221-125.eu-west-2.compute.amazonaws.com:~/todo-App

      - name: SSH into EC2, pull changes, and restart
        run: ssh -v -o StrictHostKeyChecking=no -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-18-133-221-125.eu-west-2.compute.amazonaws.com "cd ~/todo-App && git pull origin main && npm install && pm2 restart todo-App"
