name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.133.221.125 >> ~/.ssh/known_hosts

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todoapp-backend .
          docker push ${{ secrets.DOCKER_USERNAME }}/todoapp-backend

      - name: SSH into EC2 and update Docker container
        uses: appleboy/ssh-action@master
        with:
          host: 18.133.221.125
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/todoapp-backend
            docker stop todoapp-backend || true
            docker rm todoapp-backend || true
            docker run -d \
              --name todoapp-backend \
              -p 5000:5000 \
              -e POSTGRES_HOST=${{secrets.PG_HOST}} \
              -e POSTGRES_USER=${PG_USER} \
              -e POSTGRES_PASSWORD=${PG_PASSWORD} \
              -e POSTGRES_DATABASE=${PG_DATABASE} \
              -e POSTGRES_PORT=${PG_PORT} \
              ${{ secrets.DOCKER_USERNAME }}/todoapp-backend
