name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          # Get the SSH key from GitHub Actions context
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          
          # Set permissions for the private key
          chmod 600 /tmp/private_key

          # Run the SSH command with the private key
          ssh -v -o StrictHostKeyChecking=no -i /tmp/private_key ubuntu@ec2-18-133-221-125.eu-west-2.compute.amazonaws.com "cd ~/todo-App && git pull origin main"
